[package]
name = "raft-service-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
byteorder = "1.5.0"
derive_more = { version = "2.0.1", features = ["display"] }
futures-util = "0.3.31"
maplit = "1.0.2"
openraft = { git = "https://github.com/databendlabs/openraft.git", rev = "c56d043b6f10d2c0665e2fb7d7f8b1c64488e1d1", features = ["serde"] }
prost = "0.14.1"
rocksdb = { version = "0.24.0", default-features = false, features = ["bindgen-runtime"] }
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.16", features = ["full"] }
tonic = "0.14.1"
tonic-prost = "0.14.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[build-dependencies]
tonic-prost-build = "0.14.1"

[dev-dependencies]
tempfile = "3.23.0"
